-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 20:12:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BucketList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BucketList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BucketList` DEFAULT CHARACTER SET utf8 ;
USE `BucketList` ;

-- -----------------------------------------------------
-- Table `BucketList`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BucketList`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BucketList`.`BucketList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BucketList`.`BucketList` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_BucketList_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_BucketList_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `BucketList`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BucketList`.`ListItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BucketList`.`ListItem` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Description` TEXT(100) NULL,
  `BucketList_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `BucketList_ID`),
  INDEX `fk_ListItem_BucketList1_idx` (`BucketList_ID` ASC),
  CONSTRAINT `fk_ListItem_BucketList1`
    FOREIGN KEY (`BucketList_ID`)
    REFERENCES `BucketList`.`BucketList` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
